### ISSUE TITLE
Test WiremockPluginTasksSpec.'startWiremock task should start a wiremock instance' fails

### ISSUE THREAD

**Issue by jaguth** [William-Hill-Online/wiremock-gradle-plugin#1]
The Test WiremockPluginTasksSpec.'startWiremock task should start a wiremock instance' fails.  I tried using variations of plugin names and but could not get gradle to compile build.gradle without errors.  i couldn't get it to work.  Also, note that the readme doc https://github.com/William-Hill-Online/wiremock-gradle-plugin and the tests are different.  I'd love to use this, but its just not in a usable state.  could you look into it?

i'm using gradle 2.2.1

.... i can't believe my initial paragraph was so intelligible the first time around.  i fixed it.

**Comment by DavidRG13** [comment]
Hi,

Thanks a lot for pointing that tests and docs are different, I'll fix it shortly.

Regarding your issue, if you follow the docs it should work but we haven't try with that version of Gradle. Are you getting any error message?

**Comment by jaguth** [comment]
i haven't; i'll give it a try in a newer version of gradle.

**Comment by DavidRG13** [comment]
Hi @jaguth, 

I have updated the test to match the readme file. 
Did you check it with a newer version of Gradle?

**Comment by jaguth** [comment]
Thanks @DavidRG13 .  unfortunately, the code base i'm working on isn't flexible enough to make a quick switch to a newer gradle version.  however, i found that com.github.tomakehurst:wiremock-standalone:2.7.1 also meets my needs and is working for me, so i have decided to use that.

**Comment by DavidRG13** [comment]
Cool, 
closing this issue then.
